services:
  mysql:
    image: mysql
    container_name: db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - mysql
    ports:
        - 8080:8080