services:
  mysql:
    image: mysql:latest
    container_name: db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: senhasegura
      MYSQL_DATABASE: ecommerce