services:
  mysql:
    image: mysql:8.0.32
    container_name: ecommerce
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce