services:
  mysql:
    image: mysql
    container_name: db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
#
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: ecommerce
#    depends_on:
#      - db
#    ports:
#        - 8080:8080